"""Add latitude and longitude

Revision ID: 1245651603ee
Revises: 
Create Date: 2026-07-25 14:11:33.318171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1245651603ee'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lands', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('lands', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lands', 'longitude')
    op.drop_column('lands', 'latitude')
    # ### end Alembic commands ###
